# 一般設定
unbind C-b
set -g prefix C-a
set -g history-limit 100000
set -g mouse on

# ================================================
# UI
# ================================================
# 256色
set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",alacritty:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# enable visual notification
set-window-option -g monitor-activity on
set -gq allow-passthrough on
set -g visual-activity off

# refresh rate (default 15sec)
set -g status-interval 5

run "~/codes/github.com/takumi-pro/dotfiles/tmux/theme.tmux"
# ================================================

# kill
bind q kill-pane # 確認なしでpaneをkill
bind Q kill-window # 確認なしでwindowをkill

# split
bind s split-window -v -c '#{pane_current_path}'  # 横分割
bind v split-window -h -c '#{pane_current_path}'  # 縦分割

# 画面移動
# vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# window新規作成
bind c new-window -c '#{pane_current_path}'

bind W choose-tree -Zw

# セッション新規作成
bind N new-session

# セッション切替
bind w choose-tree -Zs

# セッション名変更
bind R command-prompt "rename-session '%%'"

# 画面リサイズ
bind -r H resize-pane -L 5  # 左に5px
bind -r J resize-pane -D 5  # 下に5px
bind -r K resize-pane -U 5  # 上に5px
bind -r L resize-pane -R 5  # 右に5px

# 画面入れ替え
bind h select-pane -L \; swap-pane -t !
bind j select-pane -D \; swap-pane -t !
bind k select-pane -U \; swap-pane -t !
bind l select-pane -R \; swap-pane -t !

# fzfでセッション切替
# bind j run-shell "tmux list-sessions | fzf --reverse | cut -d: -f1 | xargs tmux switch-client -t"

# 設定をリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"

